spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/login
        - id: root
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/
        - id: task
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/task/**
          filters:
            - name: AuthFilter

        - id: submit
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/submit/**
          filters:
            - name: AuthFilter
server:
  port: 3003
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true