spring:
  application:
      name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
      routes:
        - id: globalData
          uri: lb://SUBMISSION-SERVICE/globalData
          predicates:
            - Path=/globalData
        - id: auth
          uri: lb://AUTH-SERVICE/login
          predicates:
            - Path=/login

        - id: root
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/

        - id: task
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/task/**


        - id: submit
          uri: lb://SUBMISSION-SERVICE
          predicates:
            - Path=/submit/**
          filters:
            - name: AuthFilter

        - id: discussion
          uri: lb://DISCUSSION-SERVICE
          predicates:
            - Path=/graphql
          filters:
            - name: AuthFilter

server:
  port: 3333
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true